### ISSUE TITLE
Add ArchLabs distribution for pypia

### ISSUE THREAD

**Issue by gitJWR** [dagrha/pypia#16]
Wasn't sure exactly where to submit this request, so I hope this is ok.  In reference to your requested information:
1. networkmanager-openvpn
2. pacman install or packer install
3. (I couldn't follow your instructions, but the distribution is archlabs)
This is the error I get currently:
Traceback (most recent call last):
  File "pypia.py", line 240, in <module>
    install_packages(package_dict)
  File "pypia.py", line 84, in install_packages
    required_packages = package_dict['required_packages'][distro]
KeyError: 'archlabs'

**Comment by dagrha** [comment]
Hi @gitJWR, thanks for taking the time to write this up. I have now added `archlabs` to the `package_info.json` file. If you get a chance to try out the script again now that the json has been updated, please let me know if it worked for you.

**Comment by gitJWR** [comment]
It works!  Thanks so much for this.
