### ISSUE TITLE
Package not installable via pip

### ISSUE THREAD

**Issue by chrisspen** [dagrha/pypia#17]
I can't find this package at https://pypi.python.org.

Could you please upload it there? Installing via PIP is the standard way to distribute Python packages, and makes tracking versions and performing upgrades seamless. Installing via git repo is horribly inconvenient.

**Comment by dagrha** [comment]
Thanks for the comment. This has been on my mind lately-- I will definitely put this on the road map. I'd like to change a few things about how the code works and maybe add some unit tests before I start giving version numbers and distributing as a package. But it will not be long.

I realize installing by downloading the files directly is not ideal, but in the meantime I hope the instructions in the readme are straightforward enough to follow.

**Comment by dagrha** [comment]
Package is now installable via `pip install pypia` with pull request https://github.com/dagrha/pypia/pull/18
