### ISSUE TITLE
Script fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by OSLDNKKfEUVTABDLiNgk** [dagrha/pypia#2]
Here is the output from the terminal:

```
[REDACTED]@[REDACTED]:~/Downloads/PIA_install_scripts-master$ sudo sh install_ubuntu.sh
[sudo] password for [REDACTED]: 
Python already installed
Package network-manager-openvpn already installed
Please enter your PIA login: [REDACTED]
Please enter your PIA password. This gets added to your VPN config files: install_ubuntu.sh: 61: read: Illegal option -s
A password must be provided for the installation to proceed
[REDACTED]@[REDACTED]:~/Downloads/PIA_install_scripts-master$
```

**Comment by dagrha** [comment]
Thanks lauren-elise-thomas for reporting this bug. For some reason the `-s` option (which is supposed to make it such that your password is not printed in the terminal) does not work on ubuntu/lubuntu. I've patched that read function to disallow `echo` for that line, so functionality should be the same, and should be more POSIX compliant (http://stackoverflow.com/a/3980713). I've tested this on lubuntu and it seems to work as expected, so I'll close this issue for now.
