### ISSUE TITLE
Serious Issue!

### ISSUE THREAD

**Issue by chadhumphrey** [dagrha/pypia#22]
![awesomes](https://user-images.githubusercontent.com/2567249/29997913-a88e2c1a-8fdc-11e7-91cf-c480ec12923c.jpeg)

This is repo is awesome and on top of that your documentation was perfect as well!  

I wished I found it 6 hours ago! 

I would click on your affiliate link, but I already had PIA, let me know if you want me to click on anything else!

Thanks again, 

Chad

I know I'm breaking github protocol, but oh well

**Comment by dagrha** [comment]
Thanks for your support :+1:. I'm really glad you have found the repository useful! Cheers.
