### ISSUE TITLE
Please add ArchMerge distro

### ISSUE THREAD

**Issue by gitJWR** [dagrha/pypia#23]
Hello, not too long ago you added ArchLabs for me.  The maintainer of that distro has branched off and created ArchMerge which I am now using.  Aside from adding the new name, the rest should be the same as ArchLabs was.
Thanks!

**Comment by dagrha** [comment]
added with https://github.com/dagrha/pypia/commit/444c383c151affbd0d271daf4b43bd99d0cf67b6
