### ISSUE TITLE
CentOS support

### ISSUE THREAD

**Issue by a-kp** [dagrha/pypia#24]
**openvpn**
$ yum list | grep openvpn
NetworkManager-openvpn.x86_64            1:1.2.6-1.el7                   epel
NetworkManager-openvpn-gnome.x86_64      1:1.2.6-1.el7                   epel
kde-plasma-networkmanagement-openvpn.x86_64
openvpn.x86_64                           2.4.4-1.el7                     epel
openvpn-auth-ldap.x86_64                 2.0.3-14.1.el7                  epel
openvpn-devel.x86_64                     2.4.4-1.el7                     epel

**Output of get_distro()**
centos

**OS name**
$ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

**Comment by dagrha** [comment]
thanks, a-kp. added centos and updated pypi package to 0.3.2. If you get a chance I'd really appreciate if you could test to make sure it is working for you! `pip install -U pypia --no-cache-dir`
