### ISSUE TITLE
Feature to check pypia status?

### ISSUE THREAD

**Issue by cbcoder** [dagrha/pypia#39]
It would be useful to add a feature to check if PIA is connected and which location is connected to.
I don't think this exists.

**Comment by dagrha** [comment]
Hi cbcoder, thanks for taking the time to add a feature request. At this point I don't think pypia could do anything terribly sophisticated here. 

There are a couple options already available for checking network status from the command line -- for example `nmcli con show --active` would show active network connections and piping that to grep (e.g. `nmcli con show --active | grep PIA`) should get you the name of the active PIA connection. 

Is the status provided by the nmcli command above what you had in mind? 

I will close this issue for now but please feel free to add more comments to flesh out your vision for this feature, and if it's something that I think fits in well with pypia I will reopen the issue.

**Comment by cbcoder** [comment]
Thanks, that will work for sure. Cheers
