### ISSUE TITLE
Ubuntu script is missing network-manager-openvpn-gnome dependency

### ISSUE THREAD

**Issue by ghost** [dagrha/pypia#4]
The package `network-manager-openvpn-gnome` is missing.

Otherwise the error message `Could not find vpn plugin service for 'org.freedesktop.networkmanager.openvpn'` is being displayed and the connection fails.

**Comment by dagrha** [comment]
Thanks for the report. What specific OS and version are you using?

**Comment by ghost** [comment]
Plain and simple Ubuntu 16.04. Sorry, forgot to mention that in my initial post.

**Comment by dagrha** [comment]
Hi torpet, I just downloaded the latest vanilla Ubuntu 16.04, installed it in a virtual machine, ran `sudo apt update`, then ran the configuration script (`sudo sh install_ubuntu.sh`) and was unable to reproduce the error you are describing. In other words, in my test the configuration script ran fine _without_ the additional `network-manager-openvpn-gnome` package.

I'm not sure why you are experiencing that error... It seems there was some funny business going on with the `network-manager-openvpn` package (https://bugs.launchpad.net/ubuntu/+source/network-manager-openvpn/+bug/1574576)-- I am wondering if it was for some reason temporarily unavailable in the repos, yet `network-manager-openvpn-gnome` _was_ available?

**Comment by ghost** [comment]
It works fine now without network-manager-openvpn-gnome, which is weird.
I have checked multiple times including reboots before posting this bug report.
