### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by ghost** [dagrha/pypia#6]
There was no way to send you a message to thank you for creating these scripts!  I just installed openSUSE Leap 42.2 XFCE and the script was absolutely flawless!

I know this isn't an issue so please delete if it isn't wanted on the page.

Thanks again!

**Comment by dagrha** [comment]
Thanks for the feedback, drhedberg! I'm really glad that you found the scripts to be useful. It is definitely helpful to know that it worked in Leap 42.2 XFCE since I haven't tested every distro and every spin.
