### ISSUE TITLE
Manjaro 17.0 KDE - not connecting

### ISSUE THREAD

**Issue by gitJWR** [dagrha/pypia#8]
I have a fresh install of Manjaro 17.0 KDE and your script worked flawlessly to populate the connections in the network manager.  However, any connection I click on says "connecting" for a couple seconds and then stops and goes back to listed as "never used".  I'm not getting any pop up error messages at all.  Hoping you can help me troubleshoot this.  I'm not terribly experienced, but follow direction well!  Let me know if you need more info.  Thanks.
John

**Comment by dagrha** [comment]
downloading manjaro KDE right now, will try to test it out sometime today!

**Comment by gitJWR** [comment]
Wow, thanks so much!  I'll look forward to what you find.  Please let me
know if there is any more info you need from my end.


John





On Thu, Mar 9, 2017, at 11:02 AM, Dan H. wrote:

> downloading manjaro KDE right now, will try to test it out
> sometime today!
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/dagrha/pypia/issues/8#issuecomment-285413290

**Comment by dagrha** [comment]
Sorry, John, I was not able to reproduce this error. I loaded Manjaro KDE in a virtual machine, ran the script, and connected to the California server, and it connected without issue.

You might try running it again in case you typed username or password incorrectly the first time-- that would fail silently since I have no way of verifying that the password and username that you are storing in the openvpn config files are valid.

**Comment by gitJWR** [comment]
Ok, I'll give that a try--do I need to "uninstall" or edit anything
first, or will running the script overwrite whatever I did the first
time?  Also, just want to make sure there isn't any extra configuration
I'm supposed to be doing in the network manager is there?  Just run the
script and connect, right?
Thanks for taking the time to look into it--I really appreciate it!  

John





On Thu, Mar 9, 2017, at 12:01 PM, Dan H. wrote:

> Sorry, John, I was not able to reproduce this error. I loaded Manjaro
> KDE in a virtual machine, ran the script, and connected to the
> California server, and it connected without issue.
> You might try running it again in case you typed username or password
> incorrectly the first time-- that would fail silently since I have no
> way of verifying that the password and username that you are storing
> in the openvpn config files are valid.
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/dagrha/pypia/issues/8#issuecomment-285429908

**Comment by dagrha** [comment]
No uninstalling required-- config files are overwritten automatically. Shouldn't be anything else you need to do. The script should prompt you to install the `networkmanager-openvpn` package, make sure to say `y` when it prompts you

**Comment by gitJWR** [comment]
I owe you a major apology!  Just discovered that I was using an old password...twice.  Now that I have the correct info entered, it is working perfectly.  I'm really sorry for taking your time, but thanks again for that.  This is a great piece of work--so much better than other solutions I've tried.  Take care.

**Comment by dagrha** [comment]
No problem. Glad it's working for you!
